services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - SPRING_AUTH_DATASOURCE_URL=jdbc:mysql://auth-db:3306/authdb?createDatabaseIfNotExist=true
      - SPRING_AUTH_DATASOURCE_USERNAME=root
      - SPRING_AUTH_DATASOURCE_PASSWORD=authpassword

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: authpassword
      MYSQL_DATABASE: authdb
    ports:
      - "3307:3306"
    volumes:
      - auth-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  auth-data: