server:
  port: ${SPRING_APPLICATION_PORT}
  address: ${SPRING_APPLICATION_ADDRESS:127.0.0.1}

spring:
  config:
    import: classpath:security.properties, classpath:error_message.properties
  application:
    name: authentication-service

  datasource:
    name: authDataSource
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      auto-commit: false


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

cors:
  pattern: ${CORS_ALLOWED_ORIGIN_PATTERN}
  pattern-splitter: ${CORS_ALLOWED_ORIGIN_PATTERN_SPLITTER:,}

controllers:
  auth:
    baseEndpoint: /auth
    endpoints:
      register: /register
      login: /login
      refresh: /refresh
      validate: /validate
      delete: /{id}