server:
  port: 8081

spring:
  config:
    import: classpath:security.properties, classpath:error_message.properties
  application:
    name: authentication-service

  datasource:
    name: authDataSource
    url: jdbc:mysql://localhost:3307/authdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: authpassword

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml